#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Detonator_1x1x1s

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Detonator_1x1x1s.BP_Detonator_1x1x1s_C
// 0x0000 (0x0198 - 0x0198)
class UBP_Detonator_1x1x1s_C final : public UDetonatorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Detonator_1x1x1s_C">();
	}
	static class UBP_Detonator_1x1x1s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Detonator_1x1x1s_C>();
	}
};
static_assert(alignof(UBP_Detonator_1x1x1s_C) == 0x000008, "Wrong alignment on UBP_Detonator_1x1x1s_C");
static_assert(sizeof(UBP_Detonator_1x1x1s_C) == 0x000198, "Wrong size on UBP_Detonator_1x1x1s_C");

}

