#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Sensor_1sx1sx1s

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Sensor_1sx1sx1s.BP_Sensor_1sx1sx1s_C
// 0x0000 (0x0180 - 0x0180)
class UBP_Sensor_1sx1sx1s_C final : public USensorBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Sensor_1sx1sx1s_C">();
	}
	static class UBP_Sensor_1sx1sx1s_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Sensor_1sx1sx1s_C>();
	}
};
static_assert(alignof(UBP_Sensor_1sx1sx1s_C) == 0x000008, "Wrong alignment on UBP_Sensor_1sx1sx1s_C");
static_assert(sizeof(UBP_Sensor_1sx1sx1s_C) == 0x000180, "Wrong size on UBP_Sensor_1sx1sx1s_C");

}

