#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Thruster_1x1x1

#include "Basic.hpp"

#include "BrickRigs_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Thruster_1x1x1.BP_Thruster_1x1x1_C
// 0x0000 (0x01F0 - 0x01F0)
class UBP_Thruster_1x1x1_C final : public UThrusterBrickStaticInfo
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BP_Thruster_1x1x1_C">();
	}
	static class UBP_Thruster_1x1x1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Thruster_1x1x1_C>();
	}
};
static_assert(alignof(UBP_Thruster_1x1x1_C) == 0x000010, "Wrong alignment on UBP_Thruster_1x1x1_C");
static_assert(sizeof(UBP_Thruster_1x1x1_C) == 0x0001F0, "Wrong size on UBP_Thruster_1x1x1_C");

}

