#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BrickSlider

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BrickRigs_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass WBP_BrickSlider.WBP_BrickSlider_C
// 0x0010 (0x02F8 - 0x02E8)
class UWBP_BrickSlider_C : public UBrickSliderWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02E8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USpacer*                                Spacer_225;                                        // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_WBP_BrickSlider(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void UpdateSliderPosition(float NewValue);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WBP_BrickSlider_C">();
	}
	static class UWBP_BrickSlider_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_BrickSlider_C>();
	}
};
static_assert(alignof(UWBP_BrickSlider_C) == 0x000008, "Wrong alignment on UWBP_BrickSlider_C");
static_assert(sizeof(UWBP_BrickSlider_C) == 0x0002F8, "Wrong size on UWBP_BrickSlider_C");
static_assert(offsetof(UWBP_BrickSlider_C, UberGraphFrame) == 0x0002E8, "Member 'UWBP_BrickSlider_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UWBP_BrickSlider_C, Spacer_225) == 0x0002F0, "Member 'UWBP_BrickSlider_C::Spacer_225' has a wrong offset!");

}

